INPUTS: int = 2
OUTPUTS: int = 1
HIDDEN: int = 1000000

POPULATION: int = 300

COMPATIBILITY_THRESHOLD: float = 1
EXCESS_COEFFICIENT: float = 2
DISJOINT_COEFFICIENT: float = 2
WEIGHT_COEFFICIENT: float = 0.4

STEPS: float = 0.1
PERTURB_CHANCE: float = 0.9
WEIGHT_CHANCE: float = 0.3
WEIGHT_MUTATION_CHANCE: float = 0.9
NODE_MUTATION_CHANCE: float = 0.03
CONNECTION_MUTATION_CHANCE: float = 0.05
DISABLE_MUTATION_CHANCE: float = 0.1
ENABLE_MUTATION_CHANCE: float = 0.2
CROSSOVER_CHANCE: float = 0.75
