COMPATIBILITY_THRESHOLD: float = 3
EXCESS_COEFFICIENT: float = 1
DISJOINT_COEFFICIENT: float = 1
WEIGHT_COEFFICIENT: float = 0.4

PERTURB_CHANCE: float = 0.9
WEIGHT_MUTATION_CHANCE: float = 0.9
NODE_MUTATION_CHANCE: float = 0.03
CONNECTION_MUTATION_CHANCE: float = 0.05
DISABLE_MUTATION_CHANCE: float = 0.1
ENABLE_MUTATION_CHANCE: float = 0.2
CROSSOVER_CHANCE: float = 0.75
